services:
  mysql:
    image: mysql:8.0
    container_name: mysql8.0
    environment:
      MYSQL_ROOT_PASSWORD: "1qaz@WSX"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
