CREATE DATABASE cdbdev
USER SYS IDENTIFIED BY oracle
USER SYSTEM  IDENTIFIED BY oracle
EXTENT MANAGEMENT LOCAL
DEFAULT TEMPORARY TABLESPACE temp
DEFAULT TABLESPACE users
UNDO TABLESPACE undotbs1
ENABLE_PLUGGABLE_DATABASE;
