
Key Changes for Oracle 19c:
    NUMBER Data Type: Oracle uses NUMBER for numeric data. NUMBER(10, 2) means a total of 10 digits, with 2 after the decimal point.
    VARCHAR2 Data Type: Use VARCHAR2 instead of VARCHAR. VARCHAR2(255) is a common choice.
    CLOB Data Type: For large text fields, use CLOB (Character Large Object) instead of TEXT.
    DATE Data Type: Oracle's DATE type includes both date and time.
    GENERATED BY DEFAULT AS IDENTITY: This is Oracle's equivalent of auto-increment for primary keys. It automatically generates unique sequence numbers for the PersonnelID, ProductID, PartID, and SupplierID columns.
    Explicit Constraint Naming: It's good practice to name your foreign key constraints (e.g., CONSTRAINT FK_SupplierID ...).
    Foreign Key Constraint Syntax: The FOREIGN KEY constraint syntax is slightly different.
    Second SQL Statement: Data Insertion (Oracle 19c)
-- SQL statement for creating tables in Oracle 19c

-- Example: Creating a table for "Personnel"
CREATE TABLE Personnel (
    PersonnelID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Oracle's auto-increment
    FirstName VARCHAR2(255),
    LastName VARCHAR2(255),
    Department VARCHAR2(255),
    HireDate DATE,
    Salary NUMBER(10, 2) -- NUMBER is Oracle's numeric type
    -- Add more columns as needed
);

-- Example: Creating a table for "Products"
CREATE TABLE Products (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductName VARCHAR2(255),
    Description CLOB,  -- CLOB for large text
    Price NUMBER(10, 2),
    ManufacturingDate DATE
    -- Add more columns as needed
);

-- Example: Creating a table for "Parts"
CREATE TABLE Parts (
    PartID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PartName VARCHAR2(255),
    Description CLOB,
    Cost NUMBER(10, 2),
    SupplierID NUMBER,
    CONSTRAINT FK_SupplierID FOREIGN KEY (SupplierID) REFERENCES Suppliers(SupplierID) -- Explicit constraint naming
    -- Add more columns as needed
);

-- Example: Creating a table for "Suppliers"
CREATE TABLE Suppliers (
    SupplierID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SupplierName VARCHAR2(255),
    ContactName VARCHAR2(255),
    Address VARCHAR2(255),
    PhoneNumber VARCHAR2(20)
    -- Add more columns as needed
);

-- Add similar CREATE TABLE statements for the other 96 tables.


