version: "3.9"

services:
  namenode:
    image: ekinshen/hadoop:3.4.1
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "8020:8020"
    command: >
      bash -c '
        if [ ! -f /hadoop/dfs/name/current/VERSION ]; then
          hdfs namenode -format -force
        fi
        exec hdfs namenode
        '
    volumes:
      - namenode-data:/hadoop/dfs/name
    networks:
      - hadoop-net
  resourcemanager:
    image: ekinshen/hadoop:3.4.1
    container_name: resourcemanager
    hostname: resourcemanager
    depends_on:
      - namenode
    ports:
      - "8088:8088"   # YARN UI
    command: >
      bash -c "
      yarn --daemon start resourcemanager &&
      tail -f /dev/null
      "
    networks:
      - hadoop-net

  datanode1:
    image: ekinshen/hadoop:3.4.1
    container_name: datanode1
    hostname: datanode1
    depends_on:
      - namenode
    command: >
      bash -c "
      hdfs --daemon start datanode &&
      yarn --daemon start nodemanager &&
      tail -f /dev/null
      "
    networks:
      - hadoop-net
    volumes:
      - datanode1-data:/hadoop/dfs/data

  datanode2:
    image: ekinshen/hadoop:3.4.1
    container_name: datanode2
    hostname: datanode2
    depends_on:
      - namenode
    command: >
      bash -c "
      hdfs --daemon start datanode &&
      yarn --daemon start nodemanager &&
      tail -f /dev/null
      "
    networks:
      - hadoop-net
    volumes:
      - datanode2-data:/hadoop/dfs/data

  datanode3:
    image: ekinshen/hadoop:3.4.1
    container_name: datanode3
    hostname: datanode3
    depends_on:
      - namenode
    command: >
      bash -c "
      hdfs --daemon start datanode &&
      yarn --daemon start nodemanager &&
      tail -f /dev/null
      "
    networks:
      - hadoop-net
    volumes:
      - datanode3-data:/hadoop/dfs/data
networks:
  hadoop-net:

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:
  datanode3-data:
