# Bind & Security
bind 0.0.0.0
protected-mode yes
requirepass strong_redis_password

# Data directory
dir /data

# RDB Persistence
save 900 1
save 300 10
save 60 10000
dbfilename dump.rdb

# AOF Persistence (IMPORTANT)
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# Rewrite AOF automatically
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# Memory
maxmemory 2gb
maxmemory-policy allkeys-lru

# Logging
logfile ""
loglevel notice

