services:   
  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: nacos
    environment:
      MODE: single
      MYSQL_SERVICE_HOST: 172.30.0.2
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_PORT: 63306
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos123
    depends_on:
      - mysql
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge
